import React, { useMemo, useState } from 'react';
import { Link, Navigate, useNavigate, useParams } from 'react-router-dom';
import { Footer, Header, Icon, PathCard, PathVisual, SectionEyebrow } from './components';
import { BUDGET_LABELS, FORMAT_LABELS, FORMATS, getMatch, getPathById, PATHS, rankPaths, topMatches } from './data';
import { makeStages } from './plan';
import { useApp } from './state';

function BrowseControls({ query, setQuery, filter, setFilter, savedOnly, setSavedOnly, savedCount }) {
  return <div className="browse-controls"><div className="browse-search"><Icon name="search" size={19}/><input type="search" aria-label="Search business paths" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search paths, skills, or ideas..." /></div><div className="browse-filters"><button type="button" className={`filter-chip ${filter === 'all' && !savedOnly ? 'active' : ''}`} onClick={() => { setFilter('all'); setSavedOnly(false); }}>All paths</button>{FORMATS.map((format) => <button type="button" key={format.id} className={`filter-chip ${filter === format.id && !savedOnly ? 'active' : ''}`} onClick={() => { setFilter(format.id); setSavedOnly(false); }}>{format.short}</button>)}{savedCount > 0 && <button type="button" className={`filter-chip saved-filter ${savedOnly ? 'active' : ''}`} onClick={() => setSavedOnly(!savedOnly)}><Icon name="bookmark" size={14}/> Saved ({savedCount})</button>}</div></div>;
}

export function Browse() {
  const { profile, savedPaths } = useApp();
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState('all');
  const [savedOnly, setSavedOnly] = useState(false);
  const paths = useMemo(() => {
    const source = profile ? rankPaths(profile) : PATHS;
    const search = query.trim().toLowerCase();
    return source.filter((path) => (filter === 'all' || path.format === filter) && (!savedOnly || savedPaths.includes(path.id)) && (!search || `${path.title} ${path.summary} ${path.label} ${path.bestFor}`.toLowerCase().includes(search)));
  }, [profile, query, filter, savedOnly, savedPaths]);
  return <div className="site inner-page"><Header/><main className="max-wrap inner-main"><div className="browse-hero"><div><SectionEyebrow icon="sparkles">EXPLORE WHAT’S POSSIBLE</SectionEyebrow><h1>Find a path you can<br /><em>make your own.</em></h1><p>These are practical starting points, not promises of income. Explore the work, the tradeoffs, and the first move.</p><div className="browse-hero-actions">{profile ? <Link className="text-link" to="/matches">See my matches <Icon name="arrow" size={17}/></Link> : <Link className="btn btn-dark btn-sm" to="/start">Find my matches <Icon name="up" size={16}/></Link>}</div></div><div className="browse-hero-art" aria-hidden="true"><div className="browse-orbit orbit-one"/><div className="browse-orbit orbit-two"/><span>✳</span><div className="browse-art-tag art-tag-a">your skills</div><div className="browse-art-tag art-tag-b">your next step ↗</div></div></div><div className="browse-list-header"><div><span className="card-kicker">THE PATH LIBRARY</span><h2>Start exploring.</h2></div><p>{PATHS.length} paths to consider, each with a clear first step.</p></div><BrowseControls query={query} setQuery={setQuery} filter={filter} setFilter={setFilter} savedOnly={savedOnly} setSavedOnly={setSavedOnly} savedCount={savedPaths.length}/><div className="browse-count">Showing {paths.length} {paths.length === 1 ? 'path' : 'paths'}</div>{paths.length ? <div className="path-grid">{paths.map((path) => <PathCard path={path} key={path.id} showMatch={Boolean(profile)} />)}</div> : <div className="no-results"><span>✳</span><h3>No paths match those filters.</h3><p>Try a different word or show all paths again.</p><button type="button" className="btn btn-dark btn-sm" onClick={() => { setQuery(''); setFilter('all'); setSavedOnly(false); }}>Show all paths</button></div>}</main><Footer/></div>;
}

export function Matches() {
  const { profile } = useApp();
  if (!profile) return <Navigate to="/start" replace/>;
  const top = topMatches(profile, 3);
  const rest = rankPaths(profile).filter((path) => !top.some((item) => item.id === path.id));
  return <div className="site inner-page"><Header/><main className="max-wrap inner-main"><div className="results-heading"><div><SectionEyebrow icon="sparkles">MADE AROUND YOUR STARTING POINT</SectionEyebrow><h1>Here’s where <em>you could begin.</em></h1><p>These aren’t predictions. They’re a few directions to explore based on what you shared. Choose the one you want to learn about first.</p><Link className="text-link" to="/start?edit=1">Edit my answers <Icon name="up" size={17}/></Link></div><div className="results-profile"><span className="profile-topline"><Icon name="sparkles" size={15}/> YOUR STARTING POINT</span><strong>A path shaped around you.</strong><div className="profile-tags">{profile.skills?.slice(0, 2).map((skill) => <span key={skill}>{({ writing: 'Writing', design: 'Design', teaching: 'Teaching', organizing: 'Organizing', technology: 'Technology', sales: 'Sales', marketing: 'Marketing', research: 'Research', people: 'Helping people', industry: 'Industry knowledge', sourcing: 'Products' })[skill] || skill}</span>)}{profile.hours && <span>{({ 'under-5': 'Under 5 hrs/wk', '5-10': '5–10 hrs/wk', '10-20': '10–20 hrs/wk', '20-plus': '20+ hrs/wk', unsure: 'Flexible timing' })[profile.hours]}</span>}{!profile.skills?.length && !profile.hours && <span>Open to exploring</span>}</div><p>Nothing is set in stone. You can change direction anytime.</p></div></div><div className="match-note"><span><Icon name="info" size={17}/></span><p><strong>How these matches work:</strong> Suggestions use your selected skills and simple keyword matches from what you wrote, alongside your interests, time, and spending room. Nothing is hidden, and these are not predictions.</p></div><div className="section-heading match-section-heading"><div><span className="card-kicker">A GOOD PLACE TO LOOK FIRST</span><h2>Your first three paths.</h2></div><p>Different kinds of possibilities, so you can compare what feels right.</p></div><div className="path-grid">{top.map((path) => <PathCard path={path} key={path.id} showMatch featured />)}</div><div className="results-more-heading"><h2>There’s more than one way forward.</h2><Link className="text-link" to="/paths">See every path <Icon name="up" size={17}/></Link></div><div className="path-grid results-rest">{rest.slice(0, 3).map((path) => <PathCard path={path} key={path.id} showMatch />)}</div></main><Footer/></div>;
}

export function PathDetail() {
  const { id } = useParams();
  const navigate = useNavigate();
  const { profile, projects, startProject, savedPaths, toggleSaved } = useApp();
  const path = getPathById(id);
  if (!path) return <div className="site inner-page"><Header/><div className="max-wrap not-found"><span>✳</span><h1>That path wandered off.</h1><p>Let’s get you back to the good stuff.</p><Link className="btn btn-dark" to="/paths">Explore paths <Icon name="arrow" size={17}/></Link></div><Footer/></div>;
  const match = getMatch(path, profile);
  const stages = makeStages(path, profile || {});
  const alreadyStarted = projects.some((project) => project.pathId === path.id);
  const start = () => { startProject(path); navigate('/workspace'); };
  const saved = savedPaths.includes(path.id);
  return <div className="site inner-page"><Header/><main className="max-wrap path-detail"><div className="detail-breadcrumb"><Link to="/paths"><Icon name="back" size={15}/> All paths</Link><Icon name="right" size={14}/><span>{path.title}</span></div><div className="detail-hero"><div className="detail-hero-main"><div className="detail-hero-top"><span className="card-kicker"><span className="tiny-green-dot"/> {path.label}</span><button type="button" className={`detail-save ${saved ? 'saved' : ''}`} onClick={() => toggleSaved(path.id)}><Icon name="bookmark" size={16} fill={saved ? 'currentColor' : 'none'}/>{saved ? 'Saved' : 'Save path'}</button></div><h1>{path.title}<span>.</span></h1><p>{path.summary}</p><div className="detail-buttons"><button type="button" className="btn btn-dark btn-lg" onClick={start}>{alreadyStarted ? 'Continue this plan' : 'Make this my plan'} <Icon name="up" size={17}/></button><Link to="/paths" className="btn btn-outline btn-lg">Compare other paths <Icon name="arrow" size={17}/></Link></div><div className="detail-metrics"><div><Icon name="clock" size={17}/><span><strong>{path.minHours}+ hours</strong><small>a week to explore</small></span></div><div><Icon name="wallet" size={17}/><span><strong>{BUDGET_LABELS[path.budget]}</strong><small>to get started</small></span></div><div><Icon name="compass" size={17}/><span><strong>{FORMAT_LABELS[path.format]}</strong><small>type of work</small></span></div></div></div><div className="detail-hero-image"><PathVisual path={path}/></div></div>
    {profile && <div className="detail-fit"><div className="detail-fit-icon"><Icon name="sparkles" size={21}/></div><div><span className="card-kicker">WHY IT MIGHT FIT YOU · {match.level.toUpperCase()}</span><p>{match.reasons.join(' · ')}</p></div><Link to="/start?edit=1">Edit answers <Icon name="up" size={15}/></Link></div>}
    <div className="detail-content-grid"><div className="detail-main-column"><section className="detail-section"><SectionEyebrow icon="target">THE BUSINESS IN PLAIN ENGLISH</SectionEyebrow><h2>What would you actually do?</h2><p className="detail-section-intro">Start small, learn from people, and make the idea your own. Here’s one way this path could look.</p><div className="detail-explain-grid"><div><span>THE PERSON</span><p>{path.customer}.</p></div><div><span>THE PROBLEM</span><p>{path.problem}.</p></div><div><span>A FIRST OFFER</span><p>{path.firstOffer}.</p></div><div><span>ONE WAY TO TEST IT</span><p>{path.firstTest}.</p></div></div></section>
    <section className="detail-section roadmap-section"><SectionEyebrow icon="compass">A REAL PATH FROM HERE</SectionEyebrow><h2>Six stages. One step at a time.</h2><p className="detail-section-intro">Your workspace breaks each stage into small, actionable tasks, with space to keep your notes and work.</p><div className="roadmap-list">{stages.map((stage, index) => <div className="roadmap-item" key={stage.id}><span className="roadmap-number">{String(index + 1).padStart(2, '0')}</span><span className="roadmap-icon"><Icon name={stage.icon} size={19}/></span><div><strong>{stage.name}</strong><p>{stage.description}</p></div><span className="roadmap-taskcount">3 steps</span></div>)}</div></section></div>
    <aside className="detail-aside"><div className="detail-first-move"><span>✳ &nbsp; THE FIRST SMALL MOVE</span><h3>Start before you feel ready.</h3><p>{path.firstMove}</p><button type="button" className="btn btn-white" onClick={start}>{alreadyStarted ? 'Go to my plan' : 'Start this path'} <Icon name="up" size={16}/></button></div><div className="detail-honest"><span className="detail-honest-icon"><Icon name="info" size={19}/></span><h3>The honest part</h3><p>{path.caution}</p><div className="honest-foot">No income claims. No shortcuts. Just a thoughtful place to start.</div></div></aside></div></main><Footer/></div>;
}
