import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Footer, Header, Icon, SectionEyebrow } from './components';
import { BUDGETS, FORMATS, getPathById, GOALS, HOURS, SKILLS } from './data';
import { DRAFT_FIELDS, getNextTask, makeStages } from './plan';
import { useApp } from './state';

function downloadText(filename, text) {
  const blob = new Blob([text], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a'); link.href = url; link.download = filename; document.body.appendChild(link); link.click(); link.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 1000);
}

function exportMarkdown(project, path, stages, profile) {
  const lines = [`# ${path.title} — my Dayone plan`, '', `Created: ${new Date(project.createdAt).toLocaleDateString()}`, 'Progress is self-reported; this plan does not guarantee business results.', ''];
  if (profile?.location) lines.push(`Location to check local requirements: ${profile.location}`, '');
  lines.push('## My working drafts', '');
  DRAFT_FIELDS.forEach((field) => lines.push(`### ${field.label}`, (project.drafts?.[field.id] || '(Not written yet)').trim(), ''));
  lines.push('## My step-by-step plan', '');
  stages.forEach((stage) => { lines.push(`### ${stage.name}`, `${stage.description}`, ''); stage.tasks.forEach((task) => { lines.push(`- [${project.done?.[task.id] ? 'x' : ' '}] ${task.title}`, `  ${task.summary}`, `  My notes: ${(project.notes?.[task.id] || '(none yet)').replaceAll('\n', '\n  ')}`, ''); }); });
  lines.push('---', 'Made with Dayone. Local rules, payment options, and professional requirements should be checked where you live.');
  return lines.join('\n');
}

function TaskCard({ task, number, done, expanded, note, onExpand, onToggle, onNote, onCopy, onDraft }) {
  return <article className={`task-card ${expanded ? 'task-expanded' : ''} ${done ? 'task-done' : ''}`}>
    <div className="task-card-head"><button type="button" className={`task-check ${done ? 'is-checked' : ''}`} onClick={onToggle} aria-label={done ? `Mark ${task.title} incomplete` : `Mark ${task.title} complete`} title={done ? 'Mark as not done' : 'Mark as done'}>{done && <Icon name="check" size={16} strokeWidth={2.6}/>}</button><button type="button" className="task-open" aria-expanded={expanded} onClick={onExpand}><div><span className="task-index">STEP {String(number).padStart(2, '0')} <span className="task-separator">·</span> {task.time}</span><h3>{task.title}</h3><p>{task.summary}</p></div><span className="task-chevron"><Icon name={expanded ? 'chevronUp' : 'down'} size={19}/></span></button></div>
    {expanded && <div className="task-card-content"><div className="task-divider"/><div className="task-instructions"><span className="task-content-label">HOW TO DO IT</span><ul>{task.steps.map((step, index) => <li key={index}><span>{String(index + 1).padStart(2, '0')}</span><p>{step}</p></li>)}</ul></div><div className="task-prompt"><div className="task-prompt-top"><span><Icon name="sparkles" size={15}/> A HELPFUL PROMPT</span><button type="button" onClick={onCopy}><Icon name="copy" size={14}/> Copy</button></div><p>{task.prompt}</p><small>Use it as a writing exercise or with a tool you trust. Remove sensitive details before sharing.</small></div><div className="task-notes"><label htmlFor={`note-${task.id}`}>Your notes <span>Autosaved on this device</span></label><textarea id={`note-${task.id}`} value={note || ''} onChange={(event) => onNote(event.target.value)} placeholder="Write down what you tried, learned, or want to remember…"/>{task.draft && <button className="task-draft-link" type="button" onClick={onDraft}>Keep a polished version in My drafts <Icon name="arrow" size={15}/></button>}</div><div className="task-bottom"><button type="button" className={`btn ${done ? 'btn-light' : 'btn-dark'} btn-sm`} onClick={onToggle}>{done ? <><Icon name="checked" size={16}/> Done — undo</> : <>Mark this step done <Icon name="check" size={16}/></>}</button></div></div>}
  </article>;
}

function DraftsPanel({ project, saveDraft, download, toast }) {
  return <div className="workspace-panel"><div className="panel-page-head"><SectionEyebrow icon="pen">YOUR WORKING MATERIALS</SectionEyebrow><h2>The pieces you’re building.</h2><p>Keep the important parts of your business in one place. These are living drafts—you can change them as you learn.</p></div><div className="drafts-notice"><Icon name="shield" size={19}/><p>Everything here saves automatically in this browser. Download a copy if you’d like to keep it somewhere else.</p><button type="button" onClick={download}>Download <Icon name="download" size={15}/></button></div><div className="draft-grid">{DRAFT_FIELDS.map((field, index) => <div className="draft-field" key={field.id}><div className="draft-field-top"><span>0{index + 1} / WORKING DRAFT</span><Icon name="pen" size={16}/></div><label htmlFor={`draft-${field.id}`}>{field.label}</label><p>{field.hint}</p><textarea id={`draft-${field.id}`} value={project.drafts?.[field.id] || ''} onChange={(event) => saveDraft(project.id, field.id, event.target.value)} placeholder={field.placeholder}/><small><span className="tiny-green-dot"/> Saved on this device</small></div>)}</div><div className="drafts-end"><span>✳</span><div><strong>It can change as you go.</strong><p>Your first draft is a beginning, not a contract with the future.</p></div></div></div>;
}

function StartingPointPanel({ profile, project, path, onDelete }) {
  const skillLabels = profile?.skills?.map((id) => SKILLS.find((item) => item.id === id)?.label).filter(Boolean) || [];
  const formatLabels = profile?.interests?.map((id) => FORMATS.find((item) => item.id === id)?.short).filter(Boolean) || [];
  return <div className="workspace-panel"><div className="panel-page-head"><SectionEyebrow icon="compass">YOUR STARTING POINT</SectionEyebrow><h2>Start with what you have.</h2><p>Your circumstances are part of the plan, not something to work around. Change any of these whenever life changes.</p></div><div className="profile-detail-card"><div className="profile-detail-top"><span>WHAT YOU TOLD US</span><Link to="/start?edit=1">Edit my answers <Icon name="up" size={16}/></Link></div><div className="profile-detail-grid"><div><span><Icon name="sparkles" size={16}/> STRENGTHS</span><strong>{skillLabels.length ? skillLabels.join(' · ') : 'Still exploring'}</strong>{profile?.strengths && <p>{profile.strengths}</p>}</div><div><span><Icon name="clock" size={16}/> TIME EACH WEEK</span><strong>{HOURS.find((item) => item.id === profile?.hours)?.label || 'Not specified'}</strong></div><div><span><Icon name="wallet" size={16}/> SPENDING ROOM</span><strong>{BUDGETS.find((item) => item.id === profile?.budget)?.label || 'Not specified'}</strong></div><div><span><Icon name="heart" size={16}/> INTERESTS & GOALS</span><strong>{formatLabels.length ? formatLabels.join(' · ') : 'Open to possibilities'}</strong><p>{GOALS.find((item) => item.id === profile?.goal)?.label || 'No specific goal set yet'}</p></div></div>{profile?.location && <p className="profile-location"><Icon name="map" size={16}/> Based around {profile.location} — check local rules and payment options before selling.</p>}</div><div className="about-path-card"><span className="card-kicker">YOUR CURRENT PATH</span><h3>{path.title}</h3><p>{path.summary}</p>{!path.custom && <Link className="text-link" to={`/paths/${path.id}`}>Read about this path <Icon name="up" size={16}/></Link>}</div><div className="manage-plan"><div><strong>Need a different direction?</strong><p>You can explore another path without losing this one. Each plan keeps its own notes and progress.</p></div><Link className="btn btn-outline btn-sm" to="/paths">Explore paths <Icon name="arrow" size={16}/></Link></div><div className="delete-plan"><button type="button" onClick={onDelete}>Delete this plan</button><span>This removes its progress and drafts from this browser.</span></div></div>;
}

export default function Workspace() {
  const navigate = useNavigate();
  const { profile, projects, activeProjectId, setActiveProject, setSelectedStage, toggleTask, saveNote, saveDraft, removeProject } = useApp();
  const project = projects.find((item) => item.id === activeProjectId) || projects.at(-1);
  const path = project ? project.customPath || getPathById(project.pathId) : null;
  const stages = useMemo(() => path ? makeStages(path, profile || {}) : [], [path, profile]);
  const selectedStageId = project?.selectedStage || 'direction';
  const selectedIndex = Math.max(0, stages.findIndex((stage) => stage.id === selectedStageId));
  const stage = stages[selectedIndex];
  const totalTasks = stages.reduce((sum, item) => sum + item.tasks.length, 0);
  const completedTasks = stages.reduce((sum, item) => sum + item.tasks.filter((task) => project?.done?.[task.id]).length, 0);
  const nextTask = getNextTask(stages, project?.done || {}, selectedStageId);
  const stageNavRef = useRef(null);
  const [tab, setTab] = useState('plan');
  const [expandedTask, setExpandedTask] = useState(null);
  const [toast, setToast] = useState('');
  useEffect(() => {
    if (stage) setExpandedTask(stage.tasks.find((task) => !project?.done?.[task.id])?.id || stage.tasks[0]?.id);
  }, [selectedStageId, project?.id]); // Intentionally not keyed on completion; keeps the current task open.
  useEffect(() => {
    const nav = stageNavRef.current;
    if (!nav || window.innerWidth > 840) return;
    const active = nav.querySelector('.stage-nav-item.active');
    if (active) nav.scrollTo({ left: active.offsetLeft - nav.offsetLeft + active.offsetWidth / 2 - nav.clientWidth / 2, behavior: 'smooth' });
  }, [selectedStageId, tab]);
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(''), 3300); return () => clearTimeout(timer); }, [toast]);

  if (!project || !path) return <div className="site inner-page"><Header/><main className="max-wrap workspace-empty"><span className="empty-asterisk">✳</span><SectionEyebrow icon="compass">YOUR SPACE IS READY</SectionEyebrow><h1>Your next chapter starts with a first step.</h1><p>Find a path that fits or bring an idea of your own. Your plan will live here when you’re ready.</p><div><Link className="btn btn-dark btn-lg" to="/start">Find my path <Icon name="up" size={18}/></Link><Link className="btn btn-outline btn-lg" to="/paths">Explore paths <Icon name="arrow" size={18}/></Link></div></main><Footer/></div>;

  const percentage = Math.round(completedTasks / totalTasks * 100);
  const download = () => { downloadText(`${path.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'my-business'}-plan.md`, exportMarkdown(project, path, stages, profile)); setToast('Your plan was downloaded.'); };
  const copy = async (text) => { try { await navigator.clipboard.writeText(text); setToast('Copied to clipboard.'); } catch { setToast('Copy was blocked by your browser. You can select the text instead.'); } };
  const switchStage = (id) => { setSelectedStage(project.id, id); setTab('plan'); };
  const jumpToNext = () => { if (!nextTask) return; switchStage(nextTask.stage.id); setExpandedTask(nextTask.task.id); window.setTimeout(() => document.getElementById('workspace-tasks')?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 80); };
  const deletePlan = () => { if (window.confirm(`Delete “${path.title}” and its notes from this browser? This cannot be undone.`)) { removeProject(project.id); setToast('Plan deleted from this browser.'); navigate('/workspace'); } };

  return <div className="site inner-page workspace-page"><Header/><main className="max-wrap workspace-main"><div className="workspace-topline"><span>YOUR SPACE <Icon name="right" size={13}/> A WORK IN PROGRESS</span><div><span><span className="tiny-green-dot"/> Saved on this device</span><button type="button" onClick={download}><Icon name="download" size={16}/> Download plan</button></div></div>
    <div className="workspace-banner"><div className="workspace-banner-copy"><SectionEyebrow icon="sparkles">YOUR BUSINESS, YOUR WAY</SectionEyebrow><h1>Let’s make this <em>real.</em></h1><p>Your path: <strong>{path.title}</strong>. Take the next useful step, then the one after that. No need to do it all today.</p><div className="banner-tags"><span><Icon name="list" size={16}/> 6 clear stages</span><span><Icon name="clock" size={16}/> At your own pace</span></div></div><div className="workspace-progress"><div className="progress-ring" style={{ '--progress': `${percentage}%` }} role="progressbar" aria-valuenow={completedTasks} aria-valuemin={0} aria-valuemax={totalTasks} aria-label="Tasks completed"><div><strong>{percentage}%</strong><span>of steps done</span></div></div><span>{completedTasks} of {totalTasks} small steps complete</span></div></div>
    <div className="workspace-toolbar"><div className="workspace-project-select"><span>CURRENT PLAN</span>{projects.length > 1 ? <div className="project-select-wrap"><select aria-label="Switch business plan" value={project.id} onChange={(event) => { setActiveProject(event.target.value); setTab('plan'); }} >{projects.map((item) => <option value={item.id} key={item.id}>{item.title}</option>)}</select><Icon name="down" size={17}/></div> : <strong>{path.title}</strong>}</div><div className="workspace-tabs" role="tablist" aria-label="Workspace sections"><button role="tab" aria-selected={tab === 'plan'} className={tab === 'plan' ? 'tab-active' : ''} type="button" onClick={() => setTab('plan')}><Icon name="list" size={17}/> My plan</button><button role="tab" aria-selected={tab === 'drafts'} className={tab === 'drafts' ? 'tab-active' : ''} type="button" onClick={() => setTab('drafts')}><Icon name="file" size={17}/> My drafts</button><button role="tab" aria-selected={tab === 'about'} className={tab === 'about' ? 'tab-active' : ''} type="button" onClick={() => setTab('about')}><Icon name="compass" size={17}/> Starting point</button></div><Link className="workspace-add-path" to="/paths"><Icon name="plus" size={16}/> New path</Link></div>
    {tab === 'plan' ? <div className="workspace-layout"><aside className="workspace-sidebar"><div className="sidebar-title"><span>YOUR ROADMAP</span><span>0{stages.length} STAGES</span></div><div className="stage-nav" ref={stageNavRef}>{stages.map((item, index) => { const finished = item.tasks.filter((task) => project.done?.[task.id]).length; const complete = finished === item.tasks.length; const active = item.id === selectedStageId; return <button type="button" className={`stage-nav-item ${active ? 'active' : ''} ${complete ? 'complete' : ''}`} key={item.id} onClick={() => switchStage(item.id)}><span className="stage-index">{complete ? <Icon name="check" size={16}/> : String(index + 1).padStart(2, '0')}</span><span className="stage-name"><strong>{item.name}</strong><small>{finished} of {item.tasks.length} steps</small></span>{active && <Icon name="right" size={17}/>}</button>; })}</div><div className="sidebar-foot"><span className="sidebar-foot-icon"><Icon name="heart" size={19}/></span><strong>A little reminder</strong><p>It’s okay to take this one step at a time. Progress is still progress.</p></div></aside>
      <div className="workspace-center"><div className="next-step"><div className="next-step-icon"><Icon name={nextTask ? 'sparkles' : 'checked'} size={21}/></div><div><span>{nextTask ? 'YOUR NEXT SMALL STEP' : 'YOUR PLAN IS COMPLETE'}</span><strong>{nextTask ? nextTask.task.title : 'You’ve worked through every step.'}</strong><p>{nextTask ? nextTask.task.summary : 'Take what you learned and decide what to test next.'}</p></div>{nextTask && <button type="button" onClick={jumpToNext}>Go to step <Icon name="arrow" size={16}/></button>}</div>
        <div className="stage-content"><div className="stage-heading"><div className="stage-heading-icon"><Icon name={stage.icon} size={24}/></div><span>STAGE {String(selectedIndex + 1).padStart(2, '0')} / 0{stages.length}</span><h2>{stage.name}<span>.</span></h2><p>{stage.description}</p><div className="stage-outcome"><Icon name="target" size={17}/><span><strong>What you’ll come away with:</strong> {stage.outcome}</span></div></div><div className="tasks-header" id="workspace-tasks"><span>THE SMALL STEPS</span><span>{stage.tasks.filter((task) => project.done?.[task.id]).length} / {stage.tasks.length} DONE</span></div><div className="task-list">{stage.tasks.map((task, index) => <TaskCard key={task.id} task={task} number={index + 1} done={Boolean(project.done?.[task.id])} expanded={expandedTask === task.id} note={project.notes?.[task.id]} onExpand={() => setExpandedTask(expandedTask === task.id ? null : task.id)} onToggle={() => toggleTask(project.id, task.id)} onNote={(text) => saveNote(project.id, task.id, text)} onCopy={() => copy(task.prompt)} onDraft={() => { const note = project.notes?.[task.id]?.trim(); if (note && !project.drafts?.[task.draft]) { saveDraft(project.id, task.draft, note); setToast('Your note was copied into My drafts.'); } setTab('drafts'); window.setTimeout(() => document.getElementById(`draft-${task.draft}`)?.focus(), 80); }}/>)}</div><div className="stage-bottom-nav"><button type="button" disabled={selectedIndex === 0} onClick={() => switchStage(stages[selectedIndex - 1].id)}><Icon name="back" size={16}/> Previous stage</button><button type="button" disabled={selectedIndex === stages.length - 1} onClick={() => switchStage(stages[selectedIndex + 1].id)}>Next stage <Icon name="arrow" size={16}/></button></div></div>
      </div></div> : tab === 'drafts' ? <DraftsPanel project={project} saveDraft={saveDraft} download={download} /> : <StartingPointPanel profile={profile} project={project} path={path} onDelete={deletePlan} />}
    <div className="workspace-bottom-cta"><span>✳</span><div><strong>Need another perspective?</strong><p>You can explore a different direction without losing this one.</p></div><Link to="/paths">Explore paths <Icon name="up" size={17}/></Link></div>
  </main><Footer/>{toast && <div className="toast" role="status"><Icon name="checked" size={17}/>{toast}</div>}</div>;
}
